### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by mahmudemam** [fmorbini/scxmlgui#76]
Hello, 
I'm trying to build it on CentOS 6.6 but I got the following:

    [mkdir] Created dir: /work/scxmlgui/fsm-editor/bin
    [javac] Compiling 47 source files to /work/scxmlgui/fsm-editor/bin
    [javac] /work/scxmlgui/fsm-editor/src/com/mxgraph/examples/swing/editor/scxml/SCXMLEditorMenuBar.java:169: error: unmappable character for encoding UTF8
    [javac] 						"T�rsi R�bert, Alerant Zrt (Hungary)\n";
    [javac] 						  ^
    [javac] /work/scxmlgui/fsm-editor/src/com/mxgraph/examples/swing/editor/scxml/SCXMLEditorMenuBar.java:169: error: unmappable character for encoding UTF8
    [javac] 						"T�rsi R�bert, Alerant Zrt (Hungary)\n";
    [javac] 						        ^
    [javac] 2 errors

**Comment by deepindersingh68** [comment]
I am getting similar build problems when building on RED HAT 6.5. Any hints please?

**Comment by rickprice** [comment]
I simply replaced the invalid characters with something that seemed appropriate. My skills with UTF-8 don't go as far as actually fixing the issue.
